# Generated by Django 3.2.6 on 2021-09-26 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='img')),
                ('image_url', models.URLField(default='https://www.parrainages-primairepopulaire.fr/file/primaire_candidat_mystere.png')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('first_name', models.CharField(default='', max_length=32)),
                ('last_name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_ref', models.CharField(blank=True, max_length=32, unique=True)),
                ('save_date', models.DateTimeField(blank=True, null=True, verbose_name='date saved')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gov.user')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gov.candidate')),
                ('config_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gov.configref')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gov.position')),
            ],
        ),
    ]
