# Generated by Django 3.2.6 on 2021-10-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='slug',
            field=models.CharField(default='', max_length=32),
        ),
    ]
