# Generated by Django 3.2.5 on 2021-07-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0002_alter_configref_config_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configref',
            name='config_ref',
            field=models.CharField(default='cL5dJ54iPxnkTo9MNEynjnLmYS6UPKSd', max_length=32, unique=True),
        ),
    ]
