# Generated by Django 3.2.6 on 2021-10-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0002_auto_20211031_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='slug',
            field=models.CharField(max_length=32),
        ),
    ]
