# Generated by Django 3.2.5 on 2021-07-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0003_alter_configref_config_ref'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configs',
            new_name='Config',
        ),
        migrations.AlterField(
            model_name='configref',
            name='config_ref',
            field=models.CharField(default='xMQyTgCSNkYHmPkXN3tcogETaYtfu1Qr', max_length=32, unique=True),
        ),
    ]
