# Generated by Django 3.2.6 on 2021-11-02 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0003_alter_position_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='government',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gov.government'),
        ),
    ]
