# Generated by Django 3.2.5 on 2021-07-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0004_auto_20210723_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image_url',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='configref',
            name='config_ref',
            field=models.CharField(default='K4dBoIbIS8qmqkdggQrPk4qQC7MSuDAg', max_length=32, unique=True),
        ),
    ]
