# Generated by Django 3.2.5 on 2021-07-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0005_auto_20210723_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configref',
            name='save_date',
        ),
        migrations.AlterField(
            model_name='configref',
            name='config_ref',
            field=models.CharField(default='Yfetn1uglEjAOZA922E0EqiLzVQwwIA4', max_length=32, unique=True),
        ),
    ]
