# Generated by Django 3.2.5 on 2021-07-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0006_auto_20210728_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configref',
            name='config_ref',
            field=models.CharField(default='W2E92Hs3G0LGK0BtvumMX0piv3MV6oxN', max_length=32, unique=True),
        ),
    ]
