# Generated by Django 3.2.5 on 2021-07-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0007_alter_configref_config_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configref',
            name='config_ref',
            field=models.CharField(default='QNMO4eEff6vUgSYU79aFSSCmYxyaHUAO', max_length=32, unique=True),
        ),
    ]
