# Generated by Django 3.2.5 on 2021-07-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0009_alter_configref_config_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='configref',
            name='save_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date saved'),
        ),
        migrations.AlterField(
            model_name='configref',
            name='config_ref',
            field=models.CharField(default='IDl5fGwaEGUf5Q7lezpMAlycRiylZTw3', max_length=32, unique=True),
        ),
    ]
