# Generated by Django 3.2.5 on 2021-07-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0010_auto_20210728_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='image_url',
            new_name='image_file',
        ),
        migrations.AlterField(
            model_name='configref',
            name='config_ref',
            field=models.CharField(default='svDpysbb5WXna0v31gjusZ9n3wGXJNPA', max_length=32, unique=True),
        ),
    ]
