# Generated by Django 3.2.5 on 2021-07-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0011_auto_20210728_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image_url',
            field=models.URLField(default='https://www.parrainages-primairepopulaire.fr/file/primaire_candidat_mystere.png'),
        ),
        migrations.AlterField(
            model_name='configref',
            name='config_ref',
            field=models.CharField(default='qC5XQFdlRGFDbaqjM02pzIrSkEfC8urt', max_length=32, unique=True),
        ),
    ]
